### ISSUE TITLE
Bootstrap4 Support?

### ISSUE THREAD

**Issue by nicmare** [themeum/qubely#11]
At the moment you have an interesting grid layout which uses "calc" in CSS. but i rather like to include my bootstrap css/scss styles as a grid layout. Would be nice to have some kind of addon for qubely. Then once activated please unset gutter width option.

**Comment by anik4e** [comment]
@nicmare actually our grid system is percentage base not bootstrap grid based. Personally i think using bootstrap styles and grid layout is a bad thing. Because bootstrap comes with lot of css/scss it's unnecessary. If we used bootstrap then qubely will be a over weight plugin. Although I know that bootstrap's gutter width is awesome. It should be better if you suggest me how we improve our existing system. Or have you any more requirement?

**Comment by nicmare** [comment]
you can keep your grid system. bootstrap should just be an addon which replaces your grid system for ambitious devs like me, who prefer existing and established grid systems. FYI: my bootstrap css file is just 10KB gzipped. its up to the dev what he needs and what not. me personally i do not load all bootstrap assets.

**Comment by nicmare** [comment]
you also use bootstrap in your own page lol:
https://www.themeum.com/

**Comment by anik4e** [comment]
It not comes from Qubely. It comes from the theme  😋

http://prntscr.com/pu642t

**Comment by nicmare** [comment]
yes exactly. like i use it in every theme. therefore an addon would be great where qubely uses bootstrap grid instead of its own. i am not sure if we might have a missunderstanding here. are you a dev sir?! if not then you will never understand my point of view :-(

**Comment by anik4e** [comment]
Actually Qubely do not needs bootstrap components. Most of the case developer use bootstrap for Grid system and its pre-made elements. Qubely's column is percentage based and its much more flexible than the bootstrap grid system. Sorry to say, we will not give bootstrap support in near future. 

Yes i am one of the developer of Qubely. 

However thank you so much for your query.
