### ISSUE TITLE
align-wrap-wide & align-wrap-full classes?!

### ISSUE THREAD

**Issue by nicmare** [themeum/qubely#18]
Is there any reason why you do not use the default gutenberg options for having the width of a block wide or full-width?! Can you implement please?
<img width="212" alt="Bildschirmfoto 2019-11-11 um 13 59 23" src="https://user-images.githubusercontent.com/898582/68589177-8bc30300-048b-11ea-83c5-962ff461ecb7.png">

**Comment by anik4e** [comment]
Yes you are right. Gutenberg use this option we also use this settings only for Row settings. 
http://prntscr.com/pws5fj
Because only row needs "Wide width", "Align Center" and "Full Width" option. In general block it is not necessary and many setting in top settings bar going under dropdown. Thats why we prefer settings in panel.

**Comment by nicmare** [comment]
i do not agree. need this for instance for your image block too. you should decide customer and user where to use it.

**Comment by Paul979** [comment]
I agree with nicmare, please do not 'think for us' deciding where you think we need this. I like to have the flexibility to use this wherever I need, not only where Qubely thinks I need it.

And also, having to use a row every time we need full width for an element just adds unnecessary divs / code bloat. Was that considered? I hope Qubely considers code minimizing bloat!
