### ISSUE TITLE
File system not work?

### ISSUE THREAD

**Issue by rafaljosko** [themeum/qubely#7]
![image](https://user-images.githubusercontent.com/33252062/68199911-33898e00-ffbf-11e9-9e29-7ecd281e1336.png)

What is the difference between a css saving system, one is inline style and the other is a static .css file?

However, nothing changes when you choose this option - styles are always inline

**Comment by rafaljosko** [comment]
And another bug, when you go to settings in gutenberg editor

TypeError: v(...).getCurrentPostAttribute is not a function
    at Object.makePostDarty (wp-content/plugins/qubely/assets/js/qubely.min.js?ver=1.2.1:1:1173602)
    at n.value (wp-includes/js/dist/data.min.js?ver=4.4.0:1:17246)
    at t.value (wp-content/plugins/qubely/assets/js/qubely.min.js?ver=1.2.1:1:1169471)
    at qg (wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:96:196)
    at hi (wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:104:285)
    at Qg (wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:144:217)
    at Rg (wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:145:76)
    at Sc (wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:158:109)
    at Z (wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:156:492)
    at Kc (wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:155:52)

**Comment by rafaljosko** [comment]
When you add interaction to blog grid in pro version - interaction is added to all elements on page. not only to blog grid

**Comment by rafaljosko** [comment]
When you use interaction Uncaught TypeError: Cannot read property 'parentElement' of null
    at MouseTilt.reset (interaction.js?ver=1.2.1:294)

**Comment by themeum** [comment]
We'll remove this option so ignore this :)



How would you rate my reply?
Great
<https://secure.helpscout.net/satisfaction/293512506/record/2815186972/1/>
   Okay
<https://secure.helpscout.net/satisfaction/293512506/record/2815186972/2/>
   Not Good
<https://secure.helpscout.net/satisfaction/293512506/record/2815186972/3/>

--
Gianna Clark
Support Engineer
{#HS:998372378-10314#}

**Comment by rafaljosko** [comment]
What, 
Why you remove static .css   -   this is great option to speed site based on your plugin.  I can serve this file from cache -  hovering the mouse over the link, i can send static css file - so that after clicking the user will already have the file in cache.

**Comment by murshed** [comment]
Please wait for an upcoming version.

**Comment by rafaljosko** [comment]
And another problem - when you import layout - Image are not downloaded to the media, only served from your site.

**Comment by themeum** [comment]
Yes, most of the Page Builder plugins followed the same tricks.
For example: Elementor.

Let me know if you have any other questions.



How would you rate my reply?
Great
<https://secure.helpscout.net/satisfaction/293767987/record/2816530915/1/>
   Okay
<https://secure.helpscout.net/satisfaction/293767987/record/2816530915/2/>
   Not Good
<https://secure.helpscout.net/satisfaction/293767987/record/2816530915/3/>

--
Gianna Clark
Support Engineer
{#HS:999338888-10391#}

**Comment by anik4e** [comment]
@rafaljosko **File system not work?** good news is, i fixed this issue. It will be available in version 1.2.2 . But remember one thing, when you developing your site make CSS save method "head". Because **File System** sometimes cache CSS.

**Image Import Layout Issue:**
**when you import layout - Image are not downloaded to the media, only served from your site.**
I know it's happened. Actually this process has a problem to import image. 

Suppose, you import an image related block to your site. Before importing blocks we have to import the image to your media then replace the blocks image src then import the block. In this process need 10-15 average second to complete. This is the real scenario to import block.  

If anyone needs too much time to import an image related block, then he should be frustrated. Thats why most of the page builder are not importing image to media.
